### ISSUE TITLE
Fatal error on test/cases/4-8-9

### ISSUE THREAD

**Issue by brice-morin** [PavelJurasek/PHPWander#6]
Hi,

I get a fatal error (the same) trying to use your tool on cases 4, 8 and 9 (also on 14, but this is another error, I will post another issue). I am not quite sure what is the origin of the problem...

```
$ ./bin/phpwander analyse tests/cases/4 --autoload
Note: Using configuration file C:\Users\bmori\dev\PHPWander\phpwander.neon.
PHP Fatal error:  Uncaught PHPStan\ShouldNotHappenException: Internal error. in C:\Users\bmori\dev\PHPWander\vendor\phpstan\phpstan\src\Broker\Broker.php:149
Stack trace:
#0 C:\Users\bmori\dev\PHPWander\vendor\phpstan\phpstan\src\Type\ObjectType.php(161): PHPStan\Broker\Broker::getInstance()
#1 C:\Users\bmori\dev\PHPWander\vendor\phpstan\phpstan\src\Type\VerbosityLevel.php(44): PHPStan\Type\ObjectType->PHPStan\Type\{closure}()
#2 C:\Users\bmori\dev\PHPWander\vendor\phpstan\phpstan\src\Type\ObjectType.php(170): PHPStan\Type\VerbosityLevel->handle(Object(Closure), Object(Closure))
#3 C:\Users\bmori\dev\PHPWander\vendor\phpstan\phpstan\src\Type\UnionTypeHelper.php(105): PHPStan\Type\ObjectType->describe(Object(PHPStan\Type\VerbosityLevel))
#4 [internal function]: PHPStan\Type\UnionTypeHelper::PHPStan\Type\{closure}(Object(PHPStan\Type\BooleanType), Object(PHPStan\Type\ObjectType))
#5 C:\Users\bmori\dev\PHPWander\vendor\phpstan\phpstan\src\Type\UnionTypeHelper.php(106): usort(Array, Object(Closure))
#6 C:\Users\bmori\dev\PHPWander in C:\Users\bmori\dev\PHPWander\vendor\phpstan\phpstan\src\Broker\Broker.php on line 149
```

**Comment by PavelJurasek** [comment]
This one was caused by a BC break in a dependency. 
Please pull a new version of PHPWander.

**Comment by brice-morin** [comment]
OK, thanks!
