### ISSUE TITLE
Class mysqli was not found on case 14

### ISSUE THREAD

**Issue by brice-morin** [PavelJurasek/PHPWander#7]
Hi,

I got this fatal error when running case 14 (just following the instructions from the readme):

```
$ ./bin/phpwander analyse tests/cases/14 --autoload
Note: Using configuration file C:\Users\bmori\dev\PHPWander\phpwander.neon.
 0/2 [>---------------------------]   0%
 1/2 [==============>-------------]  50%PHP Fatal error:  Uncaught PHPStan\Broker\ClassNotFoundException: Class mysqli was not found while trying to analyse it - autoloading is probably not configured properly. in C:\Users\bmori\dev\PHPWander\src\Broker\Broker.php:54
Stack trace:
#0 C:\Users\bmori\dev\PHPWander\src\Analyser\NodeScopeResolver.php(175): PHPWander\Broker\Broker->getClass('mysqli')
#1 C:\Users\bmori\dev\PHPWander\src\Analyser\NodeScopeResolver.php(165): PHPWander\Analyser\NodeScopeResolver->processNode(Object(PHPCfg\Op\Expr\New_), Object(PHPWander\Analyser\Scope), Object(Closure))
#2 C:\Users\bmori\dev\PHPWander\src\Analyser\NodeScopeResolver.php(154): PHPWander\Analyser\NodeScopeResolver->processNodes(Array, Object(PHPWander\Analyser\Scope), Object(Closure))
#3 C:\Users\bmori\dev\PHPWander\src\Analyser\NodeScopeResolver.php(133): PHPWander\Analyser\NodeScopeResolver->processBlock(Object(PHPCfg\Block), Object(PHPWander\Analyser\Scope), Object(Closure))
#4 C:\Users\bmori\dev\PHPWander\src\Analyser\Analyser.php(154): PHPWander\Analyser\NodeScopeResolver-> in C:\Users\bmori\dev\PHPWander\src\Broker\Broker.php on line 54

```

**Comment by PavelJurasek** [comment]
Hello,
this one is probably because your PHP is not compiled with [mysqli](http://php.net/manual/en/book.mysqli.php) extension.

**Comment by brice-morin** [comment]
yes, indeed. Now all the cases work!
