### ISSUE TITLE
Error running tests/cases or other

### ISSUE THREAD

**Issue by Belladona-c0re** [PavelJurasek/PHPWander#9]
root@ubuntu-s-1vcpu-1gb-fra1-01:~/PHPWander# ./bin/phpwander analyse /root/DVWA/vulnerabilities/
Note: Using configuration file /root/PHPWander/phpwander.neon.
```
PHP Deprecated:  Service 'sources': option 'class' should be changed to 'factory'. in /root/PHPWander/vendor/nette/di/src/DI/Config/Definition                                   Schema.php on line 98
PHP Deprecated:  Service 'sinks': option 'class' should be changed to 'factory'. in /root/PHPWander/vendor/nette/di/src/DI/Config/DefinitionSc                                   hema.php on line 98
PHP Deprecated:  Service 'sanitizers': option 'class' should be changed to 'factory'. in /root/PHPWander/vendor/nette/di/src/DI/Config/Definit                                   ionSchema.php on line 98
PHP Deprecated:  Service 'getTaint': option 'class' should be changed to 'factory'. in /root/PHPWander/vendor/nette/di/src/DI/Config/Definitio                                   nSchema.php on line 98
PHP Fatal error:  Uncaught Nette\DI\ServiceCreationException: Service of type PHPStan\Broker\AnonymousClassNameHelper: Service of type PHPStan                                   \File\RelativePathHelper needed by $relativePathHelper in __construct() not found. Did you register it in configuration file? in /root/PHPWand                                   er/vendor/nette/di/src/DI/Resolver.php:485
Stack trace:
#0 /root/PHPWander/vendor/nette/di/src/DI/Resolver.php(186): Nette\DI\Resolver::autowireArguments(Object(ReflectionMethod), Array, Object(Nett                                   e\DI\Resolver), Object(Nette\DI\Definitions\ServiceDefinition))
#1 /root/PHPWander/vendor/nette/di/src/DI/Definitions/ServiceDefinition.php(226): Nette\DI\Resolver->completeStatement(Object(Nette\DI\Definit                                   ions\Statement))
#2 /root/PHPWander/vendor/nette/di/src/DI/Resolver.php(150): Nette\DI\Definitions\ServiceDefinition->complete(Object(Nette\DI\Resolver))
#3 /root/PHPWander/vendor/nette/di/src/DI/ContainerBuilder.php(317): Nette\DI\Resolver->completeDefinition(Object(Nette\DI\Definitions\Service                                   Definition))
#4 /root/PHPWander/vendor/nette/di/src/DI/Com in /root/PHPWander/vendor/nette/di/src/DI/Resolver.php on line 485
```

**Comment by PavelJurasek** [comment]
Hey! Try out the latest version on master branch. This repo is basically abandoned though.

**Comment by testanull** [comment]
Can you tell me where is the master branch?
